### ISSUE TITLE
Problem in the train process

### ISSUE THREAD

**Issue by yukioichida** [cognitiveailab/drrn-scienceworld#7]
Hi

I am trying to train the DRRN model using the command line in readme but I am facing some problems regarding thread management.

After some training steps (usually 300~400, it does not reach the checkpoint step so probably it is not related to the saving issue), the process hangs and cannot proceed with the following steps. Seeing all related processes in HTOP command running I suspect that some thread workers are dying for some reason and only the main process still running since there are only two threads executing after this issue.

I'm running in the following hardware:
12 cores (but I'm running with 8 environments following the parameters from readme)
Ubuntu through WSL (Windows 11)
RTX 3060 (12GB) with cuda toolkit 11.4

Probably it is not a problem in the code, but since I am not familiar with the python multiprocessing package, I could not figure out what is happening.

**Comment by yukioichida** [comment]
I just noted today that this issue occurs only when I use pytorch compiled with cuda. I tested with the pytorch cpuonly version and the training was running normally (but slower).

**Comment by yukioichida** [comment]
I just realized that there are a memory issue in the hardware that I was using. I have tested on a hardware with +12GB ram and I could execute normally, which in contrast, the WSL environment mentioned above only had 10GB ram available. 

I will close this issue.

**Comment by PeterAJansen** [comment]
This is a very helpful report of memory requirements — thanks!

**Comment by yukioichida** [comment]
Hi @PeterAJansen 

To be honest, I haven't  measure exactly the memory threshold that causes this specific problem, but I assume that the training process could not instantiate new workers processes due to the WSL memory limitation (10GB), which hangs the main process.
